<?php
/**
 * @category    Me
 * @package     Me_Shopdash
 * @author      Magevolve Ltd.
 * @copyright   Copyright (c) 2013 ShopDash Inc. (http://shopdashapp.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php $dataHelper = Mage::helper('me_shopdash'); ?>
<script type="text/javascript">
    //<![CDATA[
    function run() {
        if( confirm("<?php echo $dataHelper->__("Are you sure you want to run export? There can be performance impact during this operation.") ?>") ) {
            new Ajax.Request('<?php echo $this->getAjaxRunUrl() ?>', {
                method: 'post',
                onSuccess: function(transport){
                    var result = transport.responseText.evalJSON();
                    if (result.result == 0){
                        alert(result.msg);
                    }
                },
                on404: function(transport){
                    alert('<?php echo $dataHelper->__("URL error! 404 Not found.") ?>');
                },
                on500: function(transport){
                    alert('<?php echo $dataHelper->__("Server error! Please try again later.") ?>');
                }
            });
        }
    }
    //]]>
</script>

<?php echo $this->getButtonHtml() ?>